#! /usr/bin/env bash

# Copyright (c) 2026 Daemon Developers
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.


export script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
export repo_dir="$(git rev-parse --show-toplevel)"

print_date ()
{
	timestamp="${1}"; shift

	if date --version >/dev/null 2>&1
	then
		date -u -d "@${timestamp}" "${@}"
	else
		date -u -r "${timestamp}" "${@}"
	fi
}

export git_date="$(git log -1 --format='%ct')"
export touch_date="$(print_date "${git_date}" '+%Y-%m-%dT%H:%M:%S')"
export version_date="$(print_date "${git_date}" '+%Y%m%d')"
export version_string="${version_date}"
export product_name='saigosdk'
export release_dir="${repo_dir}/build/packages/${product_name}${NAME_SUFFIX}_${version_string}"

sum_name="${product_name}${NAME_SUFFIX}_${version_string}.sha512sum"
sign_name="${sum_name}.asc"

cd "${release_dir}"

sign_key="$(git config user.signingkey)"

gpg --yes --armor --detach-sign --faked-system-time "${git_date}!" --local-user "${sign_key}" "${sum_name}"

touch -d "${touch_date}" "${sign_name}"

gpg --verify "${sign_name}" "${sum_name}"
