# Target operating system and architecture
set(CMAKE_SYSTEM_NAME "Windows")
set(CMAKE_SYSTEM_PROCESSOR "x86")

# Target
set(CMAKE_ASM_COMPILER_TARGET "i686-w64-mingw32")
set(CMAKE_C_COMPILER_TARGET "${CMAKE_ASM_COMPILER_TARGET}")
set(CMAKE_CXX_COMPILER_TARGET "${CMAKE_ASM_COMPILER_TARGET}")

# Target prefix
set(CMAKE_FIND_ROOT_PATH "/usr/${CMAKE_ASM_COMPILER_TARGET}")

# Compilers
set(CMAKE_ASM_COMPILER "${CMAKE_ASM_COMPILER_TARGET}-gcc")
set(CMAKE_C_COMPILER "${CMAKE_ASM_COMPILER_TARGET}-gcc")
set(CMAKE_CXX_COMPILER "${CMAKE_ASM_COMPILER_TARGET}-g++")
set(CMAKE_RC_COMPILER "${CMAKE_ASM_COMPILER_TARGET}-windres")

# Find programs using host paths and headers/libraries using target paths
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
